version: '3.9'

networks:
  proxy:
    driver: bridge
  backend:
    driver: bridge
  mlflow:
    driver: bridge


volumes:
  db_datapg_postresql_mlflow: 
  db_logs_postresql_mlflow: 
  mlrun_data: 
  db_data_mysql:



services:
  pytest:
    build:
      context: ./api
    container_name: pytest
    networks:
      - backend
      - mlflow
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      DB_ENV: ${DB_ENV}
      FILE_ID: ${FILE_ID}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      WAREHOUSE_SNOWFLAKE: ${WAREHOUSE_SNOWFLAKE}
      DB_SNOWFLAKE: ${DB_SNOWFLAKE}
      SCHEMA_SNOWFLAKE: ${SCHEMA_SNOWFLAKE}
      MODEL_INFERENCE: ${MODEL_INFERENCE}
      FCST_HISTORY: ${FCST_HISTORY}
      FCST_HORIZON: ${FCST_HORIZON}
      URL_HISTORICAL: ${URL_HISTORICAL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_HOST: ${DB_MYSQL_HOST}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      TERM: ${TERM}
      BUCKET_NAME: ${BUCKET_NAME}
      MLFLOW_SERVER_PORT: ${MLFLOW_SERVER_PORT}     
    command: ["pytest", "-v"]
    ports:
      - 8000:8000
    depends_on:
      - db_mysql





  db_mysql:
    restart: always
    build: 
      context: ./databases
    container_name: db_mysql
    volumes:
      - db_data_mysql:/var/lib/mysql   
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_HOST: ${DB_MYSQL_HOST}




  mlflow_postgresql:
    restart: always
    image: postgres:13
    container_name: mlflow_postgresql
    expose:
        - 5432
    environment:
      MLFLOW_MUID: ${MLFLOW_MUID}
      MLFLOW_MGID: ${MLFLOW_MGID}
      POSTGRES_PORT: ${MLFLOW_POSTGRES_PORT}
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_HOST: ${MLFLOW_POSTGRES_HOST}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD} 
      PGDATA: ${MLFLOW_PGDATA}
      BACKEND: ${MLFLOW_BACKEND}
    volumes:
        - db_datapg_postresql_mlflow:/var/lib/postgresql/data/pgdata
        - db_logs_postresql_mlflow:/var/lib/postgresql/data/log
    networks:
        - mlflow



  mlflow_server:
    restart: always
    build:
      context: Weather_Medoc_Vineyards/Backend/mlflow
    image: mlflow_server
    container_name: mlflow_server
    ports:
        - 5001:5001
    environment:
      MLFLOW_MUID: ${MLFLOW_MUID}
      MLFLOW_MGID: ${MLFLOW_MGID}
      POSTGRES_PORT: ${MLFLOW_POSTGRES_PORT}
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_HOST: ${MLFLOW_POSTGRES_HOST}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      PGDATA: ${MLFLOW_PGDATA}
      MLFLOW_BACKEND: ${MLFLOW_BACKEND}
      HOST_MLFLOW_IP: ${HOST_MLFLOW_IP}
      MLFLOW_PORT: ${MLFLOW_PORT}
      NGINX_MLFLOW_PORT: ${NGINX_MLFLOW_PORT}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      MLFLOW_ARTIFACTS: ${MLFLOW_ARTIFACTS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
        - mlrun_data:/mlruns
    command: 
        - sh
        - -c
        - mlflow server
            --port $${MLFLOW_PORT}
            --host $${HOST_MLFLOW_IP}
            --backend-store-uri $${MLFLOW_BACKEND} 
            --default-artifact-root $${MLFLOW_ARTIFACTS}
            --serve-artifacts
    networks:
        - proxy
        - mlflow
        - backend
    depends_on:
        - db_mysql
        - mlflow_postgresql

